### PR TITLE
Initial tests for base network module

### PR DESCRIPTION
**Pull request by johnctitus**
Adds necessary files to use CircleCI for CI\CD testing of code changes.

### CODE REVIEW

**Comment by martinb3** [comment]
Looks like this one isn't followed in CircleCI, so it didn't run any tests? Going to go hit the follow button...

**Comment by martinb3** [comment]
Seems like you might have to push a commit of some kind, to trigger a build, now that CircleCI is watching the project.

**Review by stevengorrell — DISMISSED** [review]
LGTM

**Comment by johnctitus** [comment]
:(  Swear I followed it yesterday when I setup the other settings.    Thanks for fixing it @martinb3

**Review by cwgem — APPROVED** [review]
LGTM

**Review by twistedgrim — APPROVED** [review]
:+1:

**Review by martinb3 — APPROVED** [review]

**Pull request merged**
