### PR TITLE
Added option to build internet gateway

### PR DESCRIPTION
**Pull request by cygnus8595**
##### If input variables or output variables have changed or has been added, have you updated the README?

Yes, the README has been updated.

##### Do examples need to be updated based on changes?

No

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

### CODE REVIEW

**Review by stevengorrell — CHANGES_REQUESTED** [review]
We are keeping modules very specific to a single task. We already have a VPN module: https://github.com/rackspace-infrastructure-automation/aws-terraform-vpn

All things related to VPN in this pull request should be removed.

**Review by johnctitus — CHANGES_REQUESTED** [review]
Hey @cygnus8595,

Thanks for the contribution.  

The changes to the resource counts all look good, and should accomplish removing the public subnets, routes\route table and IGW.  In addition, we would also need to remove the NAT gateways, as they will be unable to work without the IGW\Public Subnets.  Also means we will need to adjust the private routes.  

Given the scope of this change, we should probably include a test to ensure everything builds correctly when the `build_igw` variable is set to false.

I also see that the changes show duplication of multiple variables.   It doesn't look like there were any intended changes there.

Once everything looks good, we will need to move this change from a fork to a branch.  Unfortunately due to security concerns, we cannot run the required tests from a fork.

**Comment by cygnus8595** [comment]
Thanks @johnctitus I don't know how the whole variables.tf file got duplicated. I'll fix that right away. It must have happened on the commit, as I was using/testing it just fine before that. I did test already with build_igw set to false (I need it for the client I'm working with, they don't use IGWs) but I'll also change it to stop building NAT gateways too if build_igw is set to false.

**Comment by cygnus8595** [comment]
> We are keeping modules very specific to a single task. We already have a VPN module: https://github.com/rackspace-infrastructure-automation/aws-terraform-vpn
> 
> All things related to VPN in this pull request should be removed.

Thanks Steven. I wasn't working with VPN so I only worked on the change I needed, but I will get VPN removed. It makes sense to have it down to a single task.

**Comment by johnctitus** [comment]
Hey @cygnus8595 I have moved these changes over to a branch and created PR #23.   It should have your changes, with a few additions to resolve test failures.  I did not remove the VPN Gateway related resources.  I think @stevengorrell 's request was due to the variable duplication mentioned earlier.  Please feel free to take a peek and weigh in if you see anything off.

Thanks again for the submission.

**Pull request closed without merging**
